development:
  adapter: postgresql
  encoding: unicode
  database: stattrack_development
  pool: 5
  timeout: 5000
  username: parallels
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: stattrack_test
  pool: 5
  timeout: 5000
  username: parallels
  password:
